development:
  adapter: mysql2
  database: raven
  host: localhost
  encoding: utf8
  username: root
  password: 
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  database: raven
  host: localhost
  encoding: utf8
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock
