# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 789eff7782fae368cbd4800e5b13f6b3c8b5ab59bf389235c0431c9bcee0cb1c7d15cdb82ca59e4f8d687ab0b1c19034bc0deeeac9612fbe3efdf80fdf6a36e9

test:
  secret_key_base: 699fade8ce76d3efc6c131de068f3589769024abec0ce843106b4e75ce82f5f9b55f6fb9091a16bef276e1fc798935fc7713fb893c3a62ea1df3748a3aeb488a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
